version: '2'

networks:
  app-tier:
    driver: bridge

services:
  kafka1:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    volumes:
      - kafka-main-broker:/bitnami/kafka
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=FFdFFr0jSfKJzjrQKZaSVA
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://localhost:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9093,1@kafka2:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  kafka2:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    volumes:
      - kafka-second-broker:/bitnami/kafka
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=FFdFFr0jSfKJzjrQKZaSVA
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://localhost:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka1:9093,1@kafka2:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true # auto creates topics if a message is send to unkown topic
  kafka-datagenerator:
    image: 'technikum/booking-datagenerator:latest'
    build: 
      context: './HotelBookingBackend/HotelBookingBackend.DataGenerator'
    environment:
      - PRODUCER_KAFKA_BOOTSTRAP_SERVER=kafka1:9092
      - PRODUCER_WAIT_TIME_BETWEEN_MESSAGES_MILLISECONDS=1000
      - PRODUCER_TOPIC_NAME=weblog
    networks:
      - app-tier
volumes:
  kafka-main-broker:
  kafka-second-broker:
